services:

  ms-config-server:
    image: "dhandapaniks/ms-config-server:0.0.3"
    container_name: "ms-config-server"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1" # Using grep, we try to check for a value UP in the Health Check API response, it will exit if it is unable to find the value UP
      interval: 10s
      timeout: 5s # In each check, it has to wait for 5 seconds
      retries: 10 # If there is a failure in healthcheck, retry for 10 times within an interval of 10 seconds
      start_period: 10s # Execute health check command or api only after 10 seconds
    extends:
      file: common-config.yml
      service: microservice-base-config
      
  ms-eurekaserver:
    image: "dhandapaniks/ms-eurekaserver:0.0.3"
    container_name: "ms-eurekaserver"
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1" # Using grep, we try to check for a value UP in the Health Check API response, it will exit if it is unable to find the value UP
      interval: 10s
      timeout: 5s # In each check, it has to wait for 5 seconds
      retries: 10 # If there is a failure in healthcheck, retry for 10 times within an interval of 10 seconds
      start_period: 10s # Execute health check command or api only after 10 seconds
    extends:
      file: common-config.yml
      service: microservice-base-config
    depends_on:
      ms-config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "ms-eurekaserver"

  ms-accounts:
    image: "dhandapaniks/ms-accounts:0.0.3"
    container_name: "ms-accounts"
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "ms-accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  ms-loans:
    image: "dhandapaniks/ms-loans:0.0.3"
    container_name: "ms-loans"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "ms-loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  ms-cards:
    image: "dhandapaniks/ms-cards:0.0.3"
    container_name: "ms-cards"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "ms-cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  dhandapaniks-xyzbank-msntwrk:
    driver: "bridge"  